language: julia
os:
    - linux
julia:
    - 0.6
services:
    - mongodb
notifications:
    email: false
before_script:
  - julia -e 'Pkg.clone("LibBSON"); Pkg.build()'
after_success:
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); cd(Pkg.dir("Mongo")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
